### ISSUE TITLE
Autorun script not executed on startup

### ISSUE THREAD

**Issue by paulhybryant** [OneCDOnly/create-autorun#1]
Installing the script works fine.

curl -sk https://raw.githubusercontent.com/onecdonly/create-autorun/master/create-autorun.sh | bash

 * script version                    : 181102
 * NAS model                         : TS-X28A (TS-212P3)
 * QTS version                       : 4.3.6 #20190308
 * default volume                    : /share/CACHEDEV1_DATA

 √ DOM partition found               : /dev/mmcblk0p5
 √ mounted (ext2) DOM partition at   : /tmp/create-autorun.T8mqmV
 √ backed-up existing autorun.sh to  : /share/CACHEDEV1_DATA/.system/autorun/autorun.sh.prev.6
 √ unmounted (ext2) DOM partition    : /tmp/create-autorun.T8mqmV

 √ autorun.sh successfully created!

I created some autorun script in the scripts folder
/share/CACHEDEV1_DATA/.system/autorun/scripts

The scripts run fine (I executed them manually after boot).
But it is not run when the system reboot

**Comment by OneCDOnly** [comment]
Hey Paul. :)

Can you confirm you've also enabled this checkbox?

> For those with QTS 4.3.x, you'll also need to let QTS know that it should permit the autorun.sh script to execute. Navigate to Control Panel -> System -> Hardware, then enable the option "Run user defined processes during startup".

https://forum.qnap.com/viewtopic.php?p=588946#p588946

**Comment by paulhybryant** [comment]
Hi @OneCDOnly 

This works now after that is turned on.
Thank you for developing and sharing this wonderful tool!
Really appreciate it.

Just out of curiosity, where can we find related documentation to develop such feature?
e.g. the boot process of QTS, where the config is stored, etc.

I am trying to develop something on my NAS too but it is so painful due to lack of information.

Thanks!

**Comment by OneCDOnly** [comment]
No worries. :)

I'm not aware of any documentation. But a lot can be found by snooping around the OS. Many tools (like this one) were developed by trial-and-error.
