### ISSUE TITLE
Installation error on QuTS Hero h5.0.1.2248

### ISSUE THREAD

**Issue by mannibis** [OneCDOnly/create-autorun#10]
This is the output of 
`curl -skL https://git.io/create-autorun | sudo bash`

```
create-autorun.sh (221208)

info: NAS model: TVS-h874 
info: QuTS version: 5.0.1 #20221215 
info: default volume: /share/ZFS1_DATA 
done: found autorun partition: /dev/sda6 
done: created mount-point: /tmp/create-autorun.wIvBKx 
done: mounted ext2 autorun partition /dev/sda6: /tmp/create-autorun.wIvBKx 
fail: Tag-file /tmp/create-autorun.wIvBKx/uLinux.conf not found! 
done: unmounted ext2 autorun partition 
done: removed mount-point: /tmp/create-autorun.wIvBKx 
```

There is no autorun directory created in the default volume .system folder. Any ideas?

**Comment by OneCDOnly** [comment]
Hey @mannibis. :)

Can you please post a list of the files in the mounted partition?

You'll need to either mount the autorun partition manually, or else edit the create-autorun.sh file to exit after it checks for the tag file.

**Comment by mannibis** [comment]
Contents of `/tmp/tmp.UUhBAY` after I mounted `/dev/sda6`

```
hero$/tmp/tmp.UUhBAY > ls -a
.  ..  lost+found  .sys_update_time
```

I'm guessing that is not the autorun partition? Mounting `/dev/sda5` produces this:

```
hero$/tmp/tmp.8JAKKi > ls -a
.  ..  lost+found  qlicense
```

**Comment by OneCDOnly** [comment]
Yes, they don't look correct. A copy of `uLinux.conf` has always been found in the same location `autorun.sh` needs to be created. 

Let's try it a different way: please use QNAP's flash mount utility, if it's available in QuTS:
```
/etc/init.d/init_disk.sh mount_flash_config
```
... then generate a directory list:
```
ls -la /tmp/nasconfig_tmp
```
... then, let's see what block device was loaded:
```
df /tmp/nasconfig_tmp
```
You could also test this location by creating an `autorun.sh` file, then seeing if you can load it via the QuTS Control Panel. I don't have a NAS running QuTS, so I can't check this myself.

**Comment by mannibis** [comment]
Hmm, weird. I get this when I try to run the init_disk.sh script:

`Mount flash configmount: special device 6 does not exist`

I do see the checkbox setting in Hardware settings to run user-defined script at startup; however, after enabling it and clicking the "View autorun.sh" link, it just brings up an empty frame.

I'm stumped--any ideas?

**Comment by OneCDOnly** [comment]
No, only thing I could suggest is manually creating a file called `autorun.sh` (with different contents) in each of the partitions you mounted previously: `/dev/sda5` and `/dev/sda6`. Then, get your QuTS Control Panel to display the `autorun.sh` contents again.

**Comment by mannibis** [comment]
OK, so it appears `/dev/sda6` is the right partition. I put an autorun.sh script in there with a comment indicating it was in /dev/sda6 and it showed up in the GUI.

I guess for QuTS you can add another case to look for `.sys_update_time`? That seems to be the only file in there.

Thanks for your help!

**Comment by OneCDOnly** [comment]
Good work mate! :)

I'll add the file you suggested as an alternative tag file. 

Cheers!
