### ISSUE TITLE
Run script on shutdown

### ISSUE THREAD

**Issue by alirezafarnoosh** [OneCDOnly/create-autorun#13]
Hello 
Any chance to add a section that run when device shutting down?
I saw a german guy uploaded an autorun.sh on the other froum but is it safe to replace the file with your file? I can provide the file in case you want me to do it

**Comment by OneCDOnly** [comment]
> Any chance to add a section that run when device shutting down?

No, as this is related to the QTS-supported `autorun.sh` file, which only runs on startup. 

If you'd like to run scripts on shutdown, please have a look at [RunLast](https://github.com/OneCDOnly/RunLast). It can run scripts after startup - or before shutdown - if you use the init.d system described. 

> I saw a german guy uploaded an autorun.sh on the other froum but is it safe to replace the file with your file? I can provide the file in case you want me to do it

This script creates an `autorun.sh` file. If you already have one, you might consider backing-it-up - then removing it - before running this script.

**Comment by alirezafarnoosh** [comment]
Thank you for responding so quickly. 
I got my answer
