### ISSUE TITLE
Permissions for user script files

### ISSUE THREAD

**Issue by GreenShadowMaker** [OneCDOnly/create-autorun#14]
Please add a reminder to README for the permissions needed on files

10-example.sh
20-example.sh

I forgot to +x, took me awhile to figure out. [mostly due to not wanting to reboot again] (not sure  what user/group they should be as best practice, mine resulted with. -rwxr-xr-x 1 admin administrators) And works now

Thanks !!

**Comment by OneCDOnly** [comment]
Hi @GreenShadowMaker :)

The README presently says:

> - `autorun.sh` is triggered at some point during NAS bootup, which then runs each executable file in the scripts directory in the default filename list order.

Files are considered executable if their executable bit has been set. 

Cheers!

**Comment by GreenShadowMaker** [comment]
Thanks for considering the documentation improvement, the note is there.  Just wasn't obvious enough reminder for me on first read / configuration / reboot.  Thanks!
