### ISSUE TITLE
error sudo: unknown user: root

### ISSUE THREAD

**Issue by himynameismate** [OneCDOnly/create-autorun#17]
I'm getting this error message:

[/] # curl -skL https://git.io/create-autorun | sudo bash
sudo: unknown user: root
sudo: unable to initialize policy plugin

I thought that on QTS the root user is admin. 
I have a TS-464

**Comment by OneCDOnly** [comment]
Hello, thanks for reporting this. 

Can you please try again but without `sudo`? 
```
curl -skL https://git.io/create-autorun | bash
```

**Comment by himynameismate** [comment]
Thanks for the quick reply, I've tried:

```
[himynameismate@NAS ~]$ curl -skL https://git.io/create-autorun | bash
fail: This script must be run with superuser privileges. Try again as: 
curl -skL https://git.io/create-autorun | sudo bash
```

**Comment by himynameismate** [comment]
nevermind, I've run 

`curl -skL https://git.io/create-autorun | sudo bash`

as my user instead of logged in as admin and it worked.

Thanks!

**Comment by OneCDOnly** [comment]
Good work. 👍🏽 

To clarify, if you login to QTS as the `admin` user (superuser) your prompt will be shown with a `#`. This means you don't need to use the `sudo` command. 

If you login as any other user, the prompt will be shown with `$`. This means sudo will be required to run scripts like `create-autorun.sh` as it needs to access restricted areas of the filesystem.
