### ISSUE TITLE
Not working on TS-231P2

### ISSUE THREAD

**Issue by stheine** [OneCDOnly/create-autorun#2]
* script version                    : 181102
 * NAS model                         : TS-X31P2 (TS-231P2)
 * QTS version                       : 4.3.6 #20190328
 * default volume                    : /share/CACHEDEV1_DATA

 √ DOM partition found               : /dev/mtd6
 X Unable to mount (ext4) DOM partition (/dev/mmcblk0p7)! Error: [mount: mounting ubi2:config on /tmp/create-autorun.HjebKJ failed: No such device]

 X autorun.sh creation failed!

**Comment by OneCDOnly** [comment]
Fixed in https://github.com/OneCDOnly/create-autorun/commit/96a9edb109d516052029d986ce952b762b48edbd
