### ISSUE TITLE
installation method soesn't work

### ISSUE THREAD

**Issue by shantee** [OneCDOnly/create-autorun#5]
Hello, 

the installation method doesn't work . It return 404.
the url should be instead 

curl -skL https://raw.githubusercontent.com/OneCDOnly/create-autorun/main/create-autorun.sh

**Comment by OneCDOnly** [comment]
Thank you @shantee - I had forgotten to update the URL shortcode after renaming the `master` branch to `main`.

I've just fixed this, and [updated](https://github.com/OneCDOnly/create-autorun/commit/ff4502474117b698bc859bcd3b407a68634c6522) the documentation. 

The correct command to download and run the script is now:
```
curl -skL https://git.io/create-autorun | bash
```
Cheers!
